title: "SWEe-book"
theme: jekyll-theme-slate

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2122S1-CS2103T-W12-2/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
